succinctlabs/rsp

crates/mpt/src/lib.rs

The underlying `construct_prefix_sets` method from `reth` inserts duplicated account address hashes. Without `freeze()` we're iterating over the duplicated items.
This change also avoids using the `keys` field directly, which isn't exposed in the canonical `reth`. One fewer reason to use a fork.
Benchmark shows that on the example Ethereum block, the cycle count for `compute_state_root` drops around 40% from `168,273,292` to `103,518,079`.

perf: deduplicate account prefix set

---

Cargo.lock
README.md
bin/guest-eth/Cargo.lock
bin/guest-op/Cargo.lock
crates/executor/guest/src/io.rs
crates/executor/guest/src/lib.rs
crates/executor/host/src/lib.rs
crates/mpt/Cargo.toml
crates/mpt/src/lib.rs
crates/primitives/src/lib.rs
crates/primitives/src/storage.rs
crates/storage/rpc-db/src/lib.rs
crates/storage/witness-db/Cargo.toml
crates/storage/witness-db/src/lib.rs

Fixes #6.
Implements the missing Merkle Patricia Trie code path:
https://github.com/succinctlabs/rsp/blob/52b27c894e29ff488038c7e698474cba739f354e/crates/mpt/src/lib.rs#L183-L184
This implementation makes use of the Geth-specific `debug_dbGet` method for preimage recovery. Also adds instructions to README specifying the Geth node requirement.

feat: mpt parent branch node conversion

---

bin/guest-eth/Cargo.lock
bin/guest-eth/Cargo.toml
bin/guest-op/Cargo.lock
bin/guest-op/Cargo.toml
crates/mpt/src/lib.rs

Fixes an issue of panicking when computing state root due to trie nodes being encoded in-place. This can happen when the common prefix is long enough and the storage value is small enough.
An Optimism block for testing is `123955997`, which panics without this patch.

fix: incorrect handling of in-place trie nodes

---

Cargo.lock
Cargo.toml
crates/mpt/Cargo.toml
crates/mpt/src/lib.rs

Fixes a bug in root hash building when multiple child nodes in a branch are deleted at the same time. This happens frequently on Ethereum, as the incentives for clearing storage slots are stronger compared to L2 networks.
The root cause is that the existing code assumes that when walking a proof, all neighbours will always end up being part of the final trie. This only works when at most one child node is being deleted by the trie, but quickly falls apart when multiple nodes are deleted, as each proof walking includes the other deleted path, resulting in both nodes ending up in the final trie.
This PR also sets up testing for the `rsp-mpt` crate, with hand-crafted test tries specifically targeting this bug. Future bug fixes shall also be accompanied by tests.
A real-world Ethereum block …

fix: state root mismatch when deleting multiple branch children

---

Cargo.lock
Cargo.toml
crates/mpt/Cargo.toml
crates/mpt/src/lib.rs

Fixes a state root computation edge case that involves inserting a new trie node that happens to have an immediate lower neighbour whose value is being updated.
When proving the absence of a node (and hence an insertion), there are cases where instead of proving a dead end on the parent branch, a neighbour node is proven instead. This happens when the neighbour node shares the same extra prefix with the node being inserted. Consider this simple trie:
- node path: `11a`
- node path: `2a`
Before any insertion, the root node is a branch node with children at slot `1` and `2`, both of which are leaf nodes.
Now, consider inserting `12b`. In order to prove its previous absence, the proof would contain the root branch node and the preimage of `11a` to show that while the slot `1` fits the new …

fix: inserting node with updated neighbour

---

Cargo.lock
Cargo.toml
bin/client-eth/Cargo.lock
bin/client-eth/Cargo.toml
bin/client-op/Cargo.lock
bin/client-op/Cargo.toml

https://github.com/alloy-rs/trie/pull/27 has been merged and there's no reason to use a fork anymore. When it gets released on we can further switch back to crates.io.

chore: replace `alloy-rs/trie` fork

---

.github/workflows/pr.yml

Outdated lock files render old commits unusable when upstreams are volatile, which can happen when:
- using Git dependencies
- dependency crates not adhering to SemVer
Adds a check that makes sure anything that goes into `main` have updated lock files.

ci: ensure lock files are up-to-date

---

crates/storage/rpc-db/src/lib.rs

Currently the host incorrect ignores proof fetching errors. This causes client execution to fail unexpectedly, and often unpredictably.

fix: proof fetching error ignored

---

crates/executor/host/src/lib.rs
crates/storage/rpc-db/src/lib.rs

RPC caches rely on requests being identical to effectively cache responses. Sorting the storage keys avoids cache misses arising from the fact that we're taking `HashMap` keys. This sorting only happens on the host side - so no perf hit on client.

perf: more caching friendly with sorted storage keys

---

Cargo.lock
Cargo.toml
bin/host/Cargo.toml
bin/host/src/execute.rs

Use `csv`'s `serialize` method, which automatically adds a header corresponding to the struct and writes the relevant data.

chore: Use CSV writer `serialize`

---

crates/executor/client/src/io.rs
crates/executor/host/src/lib.rs

The client only ever needs the state root and header hash. There's no reason to pass in the whole parent block.
Tested on block `20600000` over 5 runs yielding an average of `762,187,948` cycles, slightly down from `762,727,324` on current `main` (378ccee).

perf: use only parent header for input

---

Cargo.lock
Cargo.toml
README.md
bin/client-eth/Cargo.lock
bin/client-eth/Cargo.toml
bin/client-op/Cargo.lock
bin/client-op/Cargo.toml
bin/host/build.rs
crates/executor/client/Cargo.toml
crates/executor/client/src/custom.rs
crates/mpt/src/lib.rs
crates/primitives/Cargo.toml
crates/primitives/src/account_proof.rs
crates/storage/rpc-db/src/lib.rs
rust-toolchain

Currently, RSP uses a bunch of patches for `reth`, `revm`, and `alloy` crates, making it difficult to use latest bug fixes and improvements from upstreams.
This PR uses a new (minimal) patch for `reth` living under [`sp1-patches`](https://github.com/sp1-patches) based on a more recent [base commit](https://github.com/paradigmxyz/reth/commit/75a501e9fab65222417711edfbb2de78f406ba59). It also gets to eliminate the need for `revm` and `alloy` patches completely. Hopefully the remaining patches for `reth` will be upstreamed soon so that this fork can be removed too.
In terms of performance, unfortunately, when tested against block `20600000` for 5 runs, this PR increases cycle count from `762,127,033` on current `main` (a43182d) to `763,527,496`, for around 1.4M cycles, or _0.18%_. The …

chore: use a newer `reth` patch from `sp1-patches`

---

Cargo.lock
Cargo.toml
bin/client-eth/Cargo.lock
bin/client-eth/Cargo.toml
bin/client-linea/Cargo.lock
bin/client-linea/Cargo.toml
bin/client-op/Cargo.lock
bin/client-op/Cargo.toml
bin/host/Cargo.toml
crates/executor/host/src/lib.rs
crates/primitives/Cargo.toml
crates/primitives/src/chain_spec.rs
crates/storage/rpc-db/src/lib.rs

Upgrades the SP1 patch for `reth` to now be based on v1.0.6. Also upgrades all its relevant dependencies and resolves upstream breaking changes.
Also dropping the `alloy-trie` Git dependency patching as the fix has now been released as version `0.5.0`.
Tested against the current `main` (b1935be) and the cycle count for block `20600000` increased slightly by 0.73% from `763,497,973` to `769,074,912`.

chore: use newer patch based on reth v1.0.6

---

bin/client-eth/Cargo.lock
bin/client-eth/Cargo.toml
bin/client-linea/Cargo.lock
bin/client-linea/Cargo.toml
bin/client-op/Cargo.lock
bin/client-op/Cargo.toml

Some dependencies are instrumented with logging, and the log level evaluation happens at runtime. While the client programs don't actually print any logs to the output, such evaluation still happens silently and costs cycles. This PR disables logging at compile time to completely eliminates them from the resulting binary.
Performance improves slightly. For the block tested of `20600000`, the cycle count drops from `769,074,912` to `759,763,136` by 1.22%.

perf: statically disable logging in clients

---

.env.example
.github/workflows/pr.yml
README.md
crates/executor/host/tests/integration.rs

Adds integration test for Linea using the [updated](https://github.com/succinctlabs/rsp-tests/commit/9e76bc0d5eca334622cef3529df7ec9038033716) `rsp-tests` cache that now includes a [Linea mainnet block](https://github.com/succinctlabs/rsp-tests/blob/9e76bc0d5eca334622cef3529df7ec9038033716/blocks.json#L13).

test: integration test for Linea

---

crates/storage/witness-db/src/lib.rs

Fixes a bug that potentially allows an attacker to forge the absence of an account by withholding account proof, as currently `WitnessDb` does not fail on absence, but successfully returns `None` instead.

fix: unconstrained account absence

---

.github/workflows/pr.yml
Cargo.lock
crates/executor/client/src/io.rs
crates/executor/client/src/lib.rs
crates/executor/host/src/lib.rs
crates/storage/rpc-db/Cargo.toml
crates/storage/rpc-db/src/lib.rs

Fixes an issue that allows arbitrary block hashes to be provided for the `BLOCKHASH` opcode to use. The new implementation uses a consecutive list of parent headers leading all the way to the oldest block whose hash has been requested.

fix: unconstrained block hashes

---

Cargo.lock
bin/client-eth/Cargo.lock
bin/client-eth/Cargo.toml
bin/client-linea/Cargo.lock
bin/client-linea/Cargo.toml
bin/client-op/Cargo.lock
bin/client-op/Cargo.toml
bin/host/Cargo.toml

Changes to use the `1.2.0` release instead of RC. No significant impact on cycle count was found.

chore: bump sp1 to v1.2.0

---

README.md

This is no longer required with the new MPT implementation.

docs: remove `debug_dbGet` requirement

---

crates/executor/client/src/lib.rs
rust-toolchain
rust-toolchain.toml

Still pins toolchain for reproducibility though.

chore: remove unnecessary use of nightly rust

---

bin/client-eth/Cargo.lock
bin/client-eth/Cargo.toml
bin/client-linea/Cargo.lock
bin/client-linea/Cargo.toml
bin/client-op/Cargo.lock
bin/client-op/Cargo.toml

These patches are no longer needed as they've been merged and released to crates.io.

chore: remove unused patches

---

crates/executor/client/src/io.rs
crates/executor/client/src/lib.rs

Adds a zero-cost abstraction that allows downstream applications to build `WitnessDb` using their own client input types.

refactor: generic `WitnessInput` trait

---

Cargo.lock
Cargo.toml
bin/client-eth/Cargo.lock
bin/client-eth/Cargo.toml
bin/client-linea/Cargo.lock
bin/client-linea/Cargo.toml
bin/client-op/Cargo.lock
bin/client-op/Cargo.toml

On block `20600000` cycle count drops from `337,505,411` to `319,093,314`, or around 5.4%.

perf: replace tiny-keccak with sha3

---

crates/executor/host/src/lib.rs

The matching of Block Hash should be based on the result of RPC, for example, when facing rollup using clique, directly modifying the miner of block will lead to different final hash results. Because the miner in the program is not the same as the rpc.
Similarly, for a public chain like linear, miner needs to be modified in pre_process_block, and then miner needs to be reset in pre_finished_block (before comparing hashes).

fix: meaningless block header hash matching

---

Cargo.lock
Cargo.toml
bin/client-eth/Cargo.lock
bin/client-linea/Cargo.lock
bin/client-op/Cargo.lock
bin/host/Cargo.toml
crates/executor/client/Cargo.toml
crates/executor/client/src/error.rs
crates/executor/client/src/io.rs
crates/executor/client/src/lib.rs
crates/executor/host/Cargo.toml
crates/executor/host/src/error.rs
crates/executor/host/src/lib.rs
crates/mpt/Cargo.toml
crates/mpt/src/lib.rs
crates/mpt/src/mpt.rs
crates/primitives/Cargo.toml

Remove all uses of eyre/anyhow from the lib, and remove any panics in fns that return results

Chore(host, client, mpt): Custom error types

---

bin/client-eth/Cargo.lock
bin/client-linea/Cargo.lock
bin/client-op/Cargo.lock
bin/client-sepolia/Cargo.lock

The previous version of `kzg-rs` (0.2.3) depended on an `sp1-bls12-381` version with FD's for hooks that were deprecated as of SP1 V4. The latest `revm` has updated their dependency on `kzg-rs` to 0.2.4, which contains hooks compatible for SP1 V4.
As we depend on an older fork of `reth`, we need to manually bump the `kzg-rs` version in the `Cargo.lock`.
Doing `cargo update -p kzg-rs`:
```bash
Updating crates.io index
Locking 2 packages to latest compatible versions
Removing anyhow v1.0.93
Updating kzg-rs v0.2.3 -> v0.2.4
Removing scale-info v2.11.5
Removing scale-info-derive v2.11.5
Removing snowbridge-amcl v1.0.2
Removing sp1-lib v1.2.0
Downgrading sp1_bls12_381 v0.8.0 -> v0.8.0-sp1-4.0.0 (latest: v0.8.0)
```
to avoid this error:
> You are using reserved file descriptor 4 that is not …

fix: update kzg-rs to v0.2.4

---

bin/eth-proofs/src/cli.rs
bin/host/src/cli.rs
bin/host/src/main.rs
crates/executor/host/src/lib.rs

Restore ability to use `RPC_X` env variables. This fix has the side effect of fixing the cache that wasn't populates when only `--chain-id` was provider and `RPC_X` env was set but not taken into account.

fix: ability to populate cache

---

bin/eth-proofs/src/eth_proofs.rs

Until now, when a request to Ethproofs failed we only added a log that is hard to retrieve and analyze.
With this PR, the error will be handled normally and trigger a PG alert.

feat: properly handle errors when a request to ETH proofs fails

---

bin/host/tests/cycle_count_diff.rs
crates/executor/host/src/full_executor.rs

Sometimes, when fetching blocks with WebSockets, an event is triggered for a new block, but it's not yet available on HTTP.
Even worst,  it may happen that the latest block given by `get_block_number()` is not available with `get_block_by_number()` right away.
This PR fixes that.
Logs for reference:
```
2025-03-26T03:54:43.813177Z  INFO fetching the current block and the previous block
2025-03-26T03:54:43.875096Z  WARN Failed to execute block 22128517: RPC didnt have expected block height 22128517, retrying...
2025-03-26T03:54:43.931807Z  INFO fetching the current block and the previous block
2025-03-26T03:54:43.990532Z  WARN Failed to execute block 22128517: RPC didnt have expected block height 22128517, retrying...
2025-03-26T03:54:44.049202Z  INFO fetching the current block and the …
```

fix: better wait for the latest block

---

crates/executor/host/src/full_executor.rs

To benchmark opcodes, the user adds  the `--opcode-tracking`, that is later included as a field in the inputs send to the guest.
But when using cached input from a previous run when `--opcode-tracking` wasn't set, the input is not updated with the flag and opcodes aren't tracked.

fix: override cached opcode tracking provided flag

---

bin/eth-proofs/src/cli.rs
bin/host/src/cli.rs
bin/host/tests/cycle_count_diff.rs
crates/executor/host/src/full_executor.rs
crates/executor/host/src/lib.rs

In order to be able to verify proofs in browser, we need to be able to change the proof mode to one that supports verify in WASM (Groth16 and Plonk currently)

feat: allow to specify proof mode

---

crates/executor/host/src/host_executor.rs

Handle header `requests_hash` correctly.
Closes #120

fix: handle Pectra blocks correctly

---

crates/executor/host/src/full_executor.rs

I noticed a typo in a log message (`"sucessful"` → `"successful"`) and took the opportunity to optimize a few places where `Arc` was being cloned unnecessarily.  
For example, in `client()`, we can return a reference instead of cloning:  
```rust
fn client(&self) -> &Arc<C::Prover> {
match self {
Either::Left(ref executor) => &executor.client,
Either::Right(ref executor) => &executor.client,
}
}
```  
No functional changes, just cleaner code.

chore: fix: typo in log message + minor Arc optimization

---

Cargo.lock
Cargo.toml
README.md
bin/eth-proofs/src/cli.rs
bin/eth-proofs/src/eth_proofs.rs
bin/host/src/cli.rs
bin/host/tests/cycle_count_diff.rs
crates/executor/host/src/executor_components.rs
crates/executor/host/src/full_executor.rs
crates/executor/host/src/hooks.rs
crates/executor/host/src/lib.rs

For Eth proofs, we need to provide the cycle count. To have this information, until recently, we needed to execute the program in the zkVM. Now, with `prove_with_cycles()` added to `CudaProver`, we have access to the cycle count when proving.
This saves ~10-30s on total proving time for Eth proof.

feat: skip client execution on Eth proofs

---

crates/executor/client/src/executor.rs

Host is updated but client is not.
Similar to #121

fix: handle Pectra blocks correctly in client

---

bin/client-op/src/main.rs
bin/client/src/main.rs
bin/host/tests/cycle_count_diff.rs
crates/executor/client/src/executor.rs
crates/executor/client/src/into_primitives.rs
crates/executor/client/src/io.rs
crates/executor/client/src/lib.rs
crates/executor/host/src/executor_components.rs
crates/executor/host/src/full_executor.rs
crates/executor/host/src/host_executor.rs
crates/executor/host/tests/integration.rs

In this PR:
* Commit the full header resulting from the execution.
* Validate the header before execution.
* Added a small optim to avoid converting `Genesis` to `ChainSpec` multiple times.

feat: add validations

---

Cargo.lock
bin/client-op/Cargo.lock
bin/client/Cargo.lock
crates/mpt/Cargo.toml
crates/mpt/src/lib.rs
crates/mpt/src/mpt.rs

Allow to create a `MptNode` from an EIP-1186 proof.

feat: creates MPT from account proof

---

crates/mpt/src/mpt.rs

`MptNode` is included in SP1 Contract Call `EvmSketch` and thus need to be sync betweens threads

fix: allow to sync MptNode to another thread

---

crates/primitives/src/genesis.rs

In order to take OP stack hardforks into account.

fix: use OpChainSpec::from_genesis

---

.github/workflows/pr.yml
Cargo.lock
Cargo.toml
bin/client-op/Cargo.lock
bin/client/Cargo.lock
bin/host/genesis/11155420.json
crates/executor/host/tests/integration.rs
crates/primitives/Cargo.toml
crates/primitives/src/genesis.rs

The `ChainConfig` was failling to serialize with bincode because of Serde `flattern` and `skip_serializing_if` attributes. I created a private `serde_bincode_compat::ChainConfig` type without the attributes following the model from Alloy and Reth on bincode serialization.

fix: allow to serialize ChainConfig with bincode

---

Cargo.lock
Cargo.toml
Dockerfile
bin/client-op/Cargo.lock
bin/client-op/Cargo.toml
bin/client/Cargo.lock
bin/client/Cargo.toml
bin/continuous/src/main.rs
bin/eth-proofs/docker-compose.yml
bin/eth-proofs/src/main.rs
crates/executor/client/src/custom.rs
crates/executor/client/src/executor.rs
crates/executor/client/src/into_primitives.rs
crates/executor/client/src/io.rs
crates/executor/host/Cargo.toml
crates/executor/host/src/executor_components.rs
crates/executor/host/src/host_executor.rs
crates/executor/host/src/lib.rs
crates/primitives/src/genesis.rs
rust-toolchain.toml

chore: bump Reth to 1.5.0

---

crates/storage/rpc-db/src/execution_witness.rs

The ancestor headers must be ordered from most recent to older.

fix: order ancestor headers

---

Cargo.lock
crates/mpt/Cargo.toml
crates/mpt/examples/debug_print_state.rs
crates/mpt/src/lib.rs
crates/mpt/src/mpt.rs

Add custom `Debug` implementations for MPT types and `EthereumState` to provide cleaner, more readable output with hex-encoded data.
I am getting rid of unused SP1/RSP code from my Ethereum prover codebase, and want to share some of the useful changes I made.
- Implemented custom `Debug` for `MptNode`, `MptNodeData`, and `MptNodeReference`.
- Hex-encode all byte data (keys, values, hashes) for readability.
- Clearly label node types: `Null`, `Leaf`, `Branch`, `Extension`, `Digest`.
- Display cached references when available.
- Added example - `debug_print_state.rs` - demonstrating all MPT node variants.
- **More concise**: Hex strings instead of `[1, 2, 3, ...]` byte arrays.
- **No information loss**: All data is still present, just formatted better.
- **Easier debugging**: Node types and …

Readable Debug formatting for MPT nodes
