succinctlabs/rsp

- crates/mpt/src/lib.rs
Fixes #2.
Fixes an issue causing block state root mismatches. It turns out to be a rather common case, but most of the time the code panics on the [unimplemented Merkle Patricia Trie code path](https://github.com/succinctlabs/rsp/blob/a171bfbe9cf6a3cb6466f95289ed11ff499bd402/crates/mpt/src/lib.rs#L169-L170) way before a state root can be calculated, and therefore hiding the issue.
The current code fails with a state root mismatch error when running against certain blocks. A quick reproducer is the Optimism block `122853548`:
```console
RUST_LOG=info cargo run --bin rsp-host --release -- --block-number 122853548 --rpc-url <OPTIMISM_MAINNET_RPC_URL>
```
which fails with:
```log
2024-08-12T06:38:41.224368Z  INFO rsp_host_executor: validating the block post execution …
```
> fix: extension trie node incorrectly ignored

- Cargo.lock
- README.md
- bin/host/Cargo.toml
> chore: rename `rsp-host` to `rsp`

- Cargo.lock
- bin/client-eth/Cargo.lock
- bin/client-eth/Cargo.toml
- bin/client-op/Cargo.lock
- bin/client-op/Cargo.toml
- bin/host/Cargo.toml
- Updated the SP1 zkVM and SDK versions to 1.1.1
- Added the k256 and sha patch to the programs, now transaction recovery takes significantly less cycles!
> chore: Updated SP1 sdk version and added ecdsa and sha patch to programs.

- crates/mpt/src/lib.rs
Fixes a rather rare state root computation edge case that affected Ethereum mainnet block `20527346`.
The contract deployed at `0xfd8C3ACD4187aA14FE7D7e28E498dd6e5Df4A1D0` had exactly 3 storage slots used before this block. All these slots shared no prefix, and therefore sit on the root branch node as 3 child nodes.
The block cleared 2 out of the 3 storage slots, leaving only one slot behind. This slot then becomes a root leaf node. That is, the root node turns from a branch node into a leaf node. In general, this bug is triggered when the only one child of the root branch node is left.
This process of turning a parent branch node into a leaf node has been implemented with #7. However, the very _condition_ of checking whether such a conversion is needed stayed incorrect. When checking for …
> fix: deleteing root branch node neighbours

- Cargo.lock
- README.md
- bin/host/Cargo.toml
Adds basic CUDA support that needs to be turned on or off at compile time. Might want to make it a runtime toggle in the future.
> feat: use CUDA support from SP1 SDK

- Cargo.lock
- bin/client-eth/Cargo.lock
- bin/client-eth/Cargo.toml
- bin/client-op/Cargo.lock
- bin/client-op/Cargo.toml
- bin/host/Cargo.toml
Upgrades SP1. Tested proof generation with CUDA.
> chore: upgrade SP1 to v1.2.0-rc1

- .github/workflows/pr.yml
Adds `cargo fmt` and `cargo clippy` checks on CI.
> ci: rustfmt and clippy

- crates/executor/client/src/io.rs
There's no good reason for taking ownership here via `std::mem::take`.
On block `20600000`, cycle count drops very slightly from `338,311,316` to `338,218,654` compared to current `main` (84e643196c90aa7dba3ae7c2805f37798ce29999).
While the cycle saving is insignificant, this change makes the code nicer so it's still a win.
> perf: do not take ownership of state_requests

- .gitignore
- Cargo.lock
- README.md
- bin/client-eth/Cargo.lock
- bin/client-eth/Cargo.toml
- bin/client-linea/Cargo.lock
- bin/client-linea/Cargo.toml
- bin/client-op/Cargo.lock
- bin/client-op/Cargo.toml
- bin/host/Cargo.toml
- bin/host/build.rs
- bin/host/src/main.rs
Also has some small doc fixes.
> chore: bump sp1 to 3.0.0

- Cargo.lock
- bin/client-eth/Cargo.lock
- bin/client-eth/Cargo.toml
- bin/client-linea/Cargo.lock
- bin/client-linea/Cargo.toml
- bin/client-op/Cargo.lock
- bin/client-op/Cargo.toml
- bin/host/Cargo.toml
- bin/host/src/main.rs
Bumping sp1 to v4. Also updated sp1-patches dependencies.
> feat: bump sp1 to v4

- .gitignore
- README.md
- bin/host/src/main.rs
- crates/executor/client/src/lib.rs
I know it's very (very x 10) minor but well, I've guessed that better PR that discarding as I don't like to have non clean git tree.
> Add .vscode to gitignore and fix 3 typos

- Cargo.lock
- README.md
- bin/eth-proofs/Cargo.toml
- bin/eth-proofs/src/main.rs
- bin/eth-proofs/src/pager_duty.rs
- bin/host/Cargo.toml
- bin/host/src/execute.rs
- crates/executor/host/Cargo.toml
Remove dependency to `pagerduty-rs` that what not working and send alerts manually
> feat: Send alerts correctly to PagerDuty

- Cargo.lock
- Justfile
- bin/eth-proofs/Cargo.toml
- bin/eth-proofs/src/eth_proofs.rs
- crates/executor/host/src/alerting.rs
This PR updates the `eth-proofs` program to retry on failing requests to update proving status to Ethproofs.
> feat: retry when reporting proving status to Ethproofs fail

- Justfile
- bin/client-op/src/main.rs
- bin/client/src/main.rs
- bin/host/src/cli.rs
- bin/host/src/execute.rs
- bin/host/src/main.rs
- bin/host/tests/cycle_count_diff.rs
- crates/executor/client/src/executor.rs
In this PR:
* Added prover prover gas tracking
* Added inputs deserialization cycle count tracking
Both were added to the report CSV and the table in CI.
> feat: handle prover gas reporting

- README.md
I believe these have been moved https://docs.succinct.xyz/docs/sp1/getting-started/install
> docs: update getting started link

- Cargo.lock
- Cargo.toml
- bin/client-op/Cargo.lock
- bin/client-op/Cargo.toml
- bin/client/Cargo.lock
- bin/client/Cargo.toml
- bin/host/tests/cycle_count_diff.rs
- crates/executor/client/Cargo.toml
- crates/executor/client/src/custom.rs
- crates/executor/client/src/executor.rs
- crates/executor/client/src/into_primitives.rs
- crates/executor/client/src/tracking/block_executor.rs
- crates/executor/host/src/executor_components.rs
- crates/executor/host/src/full_executor.rs
- crates/executor/host/src/host_executor.rs
- crates/executor/host/tests/integration.rs
- crates/primitives/src/genesis.rs
- crates/storage/rpc-db/src/lib.rs
> feat: bump Reth version to v1.3.3

- README.md
> docs: add docs about precompiles/opcodes tracking

- Cargo.lock
- Cargo.toml
- bin/client-op/Cargo.lock
- bin/client-op/Cargo.toml
- bin/client/Cargo.lock
- bin/client/Cargo.toml
- bin/host/tests/cycle_count_diff.rs
Bump Reth to v1.3.4 and SP1 to 4.1.6
> chore: update Reth to v1.3.4 and SP1 to 4.1.6

- .github/workflows/cycle-tracking.yml
- Cargo.lock
- Cargo.toml
- bin/client-op/Cargo.lock
- bin/client/Cargo.lock
- crates/executor/client/src/custom.rs
> chore: update Reth to v1.3.10

- crates/executor/client/src/executor.rs
- crates/executor/client/src/into_primitives.rs
Use `validate_body_against_header_op()` instead of `validate_body_against_header()` on OP chains.
> fix: use validate_body_against_header_op on OP chains

- Cargo.lock
- Cargo.toml
- bin/client-op/Cargo.lock
- bin/client/Cargo.lock
- bin/continuous/src/main.rs
- bin/host/src/cli.rs
- bin/host/src/execute.rs
- bin/host/tests/cycle_count_diff.rs
- crates/executor/host/src/alerting.rs
- crates/executor/host/src/full_executor.rs
- crates/executor/host/src/host_executor.rs
- crates/mpt/src/execution_witness.rs
- crates/mpt/src/mpt.rs
- crates/primitives/src/genesis.rs
- rust-toolchain.toml
> chore: bump reth to 1.6.0

- .github/workflows/cycle-tracking.yml
- .github/workflows/pr.yml
- crates/executor/host/tests/integration.rs
- crates/primitives/src/chain_spec.rs
- crates/primitives/src/genesis.rs
> feat: add holesky

- Cargo.lock
- Cargo.toml
- bin/client-op/Cargo.lock
- bin/client/Cargo.lock
> chore: bump Reth to v1.8.1
